# Generated by Django 5.1 on 2025-02-25 15:20

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        CreateExtension("postgis"),
    ]
