# Generated by Django 5.1 on 2025-03-21 17:19

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("commons", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
    ]
