# Generated by Django 5.1.7 on 2025-03-26 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
        ("schedules", "0003_schedule_booking_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="schedule",
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={"default_related_name": "activities"},
        ),
        migrations.AddField(
            model_name="activity",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "recurring"), (1, "one-time")],
                default=None,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="RecurringActivity",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="schedules.schedule",
                    ),
                ),
            ],
            options={
                "default_related_name": "recurring_activities",
            },
            bases=("activities.activity",),
        ),
    ]
