# Generated by Django 5.1 on 2025-01-20 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="user",
            new_name="created_by",
        ),
    ]
