# Generated by Django 5.1 on 2025-02-08 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_rename_user_activity_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="is_published",
        ),
    ]
