# Generated by Django 5.1 on 2025-01-15 16:19

from django.conf import settings
from django.db import migrations, models


def delete_extra_interactions(apps, schema_editor):
    User = apps.get_model("users", "User")
    db_alias = schema_editor.connection.alias

    users_all = User.objects.using(db_alias).all()
    for user in users_all:
        last_interaction_pk = user.interactions.aggregate(pk=models.Max("pk"))["pk"]
        extra_interactions = user.interactions.exclude(pk=last_interaction_pk).all()
        extra_interactions.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_interaction_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Like"), (1, "Dislike"), (2, "Watch Later")]
            ),
        ),
        migrations.RunPython(
            delete_extra_interactions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name="interaction",
            unique_together={("activity", "user")},
        ),
    ]
