# Generated by Django 5.1 on 2025-02-26 08:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_remove_activity_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
