# Generated by Django 5.1 on 2025-01-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0004_alter_interaction_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="activities/")),
                ("order", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
