# Generated by Django 5.1 on 2025-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workday",
            name="day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "monday"),
                    (1, "tuesday"),
                    (2, "wednesday"),
                    (3, "thursday"),
                    (4, "friday"),
                    (5, "saturday"),
                    (6, "sunday"),
                ]
            ),
        ),
    ]
