# Generated by Django 5.1 on 2025-03-17 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0002_alter_workday_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="booking_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
