# Generated by Django 5.1 on 2025-01-20 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_rename_user_activity_created_by"),
        ("interactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="interaction",
            old_name="user",
            new_name="created_by",
        ),
        migrations.AlterUniqueTogether(
            name="interaction",
            unique_together={("activity", "created_by")},
        ),
    ]
