# Generated by Django 5.1 on 2025-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
