# Generated by Django 5.1 on 2025-02-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket_types", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="ticket_types.tickettype",
            ),
        ),
        migrations.DeleteModel(
            name="TicketType",
        ),
    ]
