# Generated by Django 5.1 on 2025-02-08 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_remove_activity_is_published"),
        ("ticket_types", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tickettype",
            unique_together={("name", "activity")},
        ),
    ]
